### ISSUE TITLE
Latest update causes SIGIOT errors

### ISSUE THREAD

**Issue by Brackston** [joe7575/signs_bot#20]
Not sure what happened but the last update leaves bots in map after a server crash, removing the artifacts (leftover bots from previous crash) while bots are running crashed our server. Not sure of the problem. our Server had plenty of ram (32Gig) so a SIGIOT is strange,
![Leap frog](https://user-images.githubusercontent.com/26545939/161118303-f82c5890-dbb5-4c8b-877d-f087c2ec115a.png)

**Comment by nixnoxus** [comment]
> .. leaves bots in map after a server crash
This this problem has existed for some time. 

See https://github.com/joe7575/signs_bot/pull/21

so it must not necessarily be related to the last update

**Comment by debagos** [comment]
Yes, we must distinguish here between two things.
1) Fatal crash.
2) The leftover bots after a fatal error.

Number 2 happens when the server dies without shutting down gracefully. @nixnoxus explained the problem very detailed in #21 
But number 1, the fatal crashes, I can't really explain them. All information I have is that a sub process of Minetest dies and then the main process panics and kills itself instantly with a SIGIOT, which is basically a abort signal (MT returns that when a sub process dies). So no shutdown is executed, the whole server is instantly death.

I am not too sure if this really is a problem with this mod, because a mod should never be able to crash the Lua process and furthermore there are signs that using nested interrupts in Mesecons Lua Controller crash the server the same way.

**Comment by joe7575** [comment]
A `std::bad_alloc` is something you should report in the [minetest repo](https://github.com/minetest/minetest/issues) or in the forum.

**Comment by debagos** [comment]
Hence this seems like an engine problem, I'll close this issue.
I created an issue in the Minetest repo: https://github.com/minetest/minetest/issues/12163

**Comment by debagos** [comment]
Hence this seems like an engine problem, we should close this issue.
I created an issue in the Minetest repo: https://github.com/minetest/minetest/issues/12163

**Comment by joe7575** [comment]
Thanks for the info
