### ISSUE TITLE
bot can´t pass bot_flap in certain case

### ISSUE THREAD

**Issue by blaboing** [joe7575/signs_bot#34]
bot fails to use bot_flap if first `turn_*` command is followed by a `move X` command and a third command.
```
turn_left
move 2
turn_right
```
![screenshot_20231006_070643](https://github.com/joe7575/signs_bot/assets/56389853/e588722b-8794-4192-b456-f19aaa3a6252)

It´s a pretty specific case because it doesn´t fail if
- turn_* isn´t the first command used in the script, `turn_right turn_around` would work to go left
- there isn´t a third command
- `cond_move` is used instead of `move X`
- another command is used before `move X`

**Comment by joe7575** [comment]
The bot can't run through the bot_flap with a `move x` command, only with a `cond_move` command. 
This is no bug, but I have to improve the manual.

**Comment by blaboing** [comment]
You might want to test that ingame first.

left bot_flap doesn´t work, right does
```
turn_left
move 2
turn_around
move 2
```
or 
right bot_flap doesn´t work, left does
```
turn_right
move 2
turn_around
move 2
```
![grafik](https://github.com/joe7575/signs_bot/assets/56389853/2255b9a3-e5d9-438a-b435-135e4ac62e65)

**Comment by joe7575** [comment]
As already written: The bot can run through the bot_flap with a `cond_move` only.
If the bot runs the following commands:

```
turn_right
move 2
turn_around
move 2
```

the following happens:

- the bot turns right
- the bot can't execute the `move 2` because of the obstacle
- the bot turns around
- the bot can't execute the `move 2` because of the obstacle
- the bot falls into the default behaviour, which is the `cond_move` and therefore runs through the bot_flap

**Comment by blaboing** [comment]
> As already written: The bot can run through the bot_flap with a `cond_move` only. If the bot runs the following commands:
without the necessary detail....
>     * the bot falls into the default behaviour, which is the `cond_move` and therefore runs through the bot_flap
In that case yesh not a bug
